# Generated by Django 5.1.3 on 2025-01-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OAuthClientConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("OPENEDX", "Open edX Instance"),
                            ("OTHER", "Other Service"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(help_text="Service base URL")),
                ("_client_id", models.CharField(db_column="client_id", max_length=255)),
                (
                    "_client_secret",
                    models.CharField(db_column="client_secret", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "OAuth Client Configuration",
                "verbose_name_plural": "OAuth Client Configurations",
                "indexes": [
                    models.Index(
                        fields=["service_type"], name="oauth_clien_service_7cd5cb_idx"
                    )
                ],
            },
        ),
    ]
