# Generated by Django 5.1.3 on 2025-01-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth_clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthclientconfig",
            name="_client_id",
            field=models.TextField(db_column="client_id"),
        ),
        migrations.AlterField(
            model_name="oauthclientconfig",
            name="_client_secret",
            field=models.TextField(db_column="client_secret"),
        ),
    ]
