# Generated by Django 5.2 on 2025-05-11 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultQuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_list_ids",
                    models.JSONField(help_text="References to MongoDB question IDs."),
                ),
                (
                    "learning_objective",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.learningobjective",
                    ),
                ),
            ],
            options={
                "verbose_name": "Default Question Set",
                "verbose_name_plural": "Default Question Sets",
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_id", models.CharField(db_index=True, max_length=255)),
                (
                    "learning_objective",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.learningobjective",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Category",
                "verbose_name_plural": "Question Categories",
            },
        ),
        migrations.CreateModel(
            name="UserQuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_list_ids",
                    models.JSONField(help_text="References to MongoDB question IDs."),
                ),
                ("grading_mode", models.BooleanField(default=False)),
                (
                    "learning_objective",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.learningobjective",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_sets",
                        to="users.edxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Question Set",
                "verbose_name_plural": "User Question Sets",
            },
        ),
    ]
