services:
  # Development PostgreSQL - inherits from base
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    container_name: edu-vault-db-dev
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development Django application
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    build: .
    container_name: edu-vault-web-dev
    command: >
      sh -c "python manage.py migrate --settings=src.config.django.dev &&
             uvicorn src.config.asgi:application --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app  # Mount current directory for live editing
      - /app/.venv  # Exclude virtual environment from mounting
    ports:
      - "${WEB_PORT}:8000"
    stdin_open: true
    tty: true

  # Development Celery worker
  celery:
    extends:
      file: docker-compose.base.yml
      service: celery
    container_name: edu-vault-celery-dev
    build: .
    volumes:
      - .:/app
      - /app/.venv

# Add the missing networks and volumes sections

volumes:
  postgres_data:

networks:
  edu-vault-network:
    external: true
