services:
  # Production PostgreSQL
  db:
    restart: unless-stopped


  # Production Django application
  web:
    build: .
    command: >
      sh -c "python manage.py migrate --settings=src.config.django.production &&
             python manage.py collectstatic --noinput --settings=src.config.django.production &&
             uvicorn src.config.asgi:application --host 0.0.0.0 --port 8000 --workers 2"
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - /home/virtu-educate/ed_vault_static:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=src.config.django.production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    restart: unless-stopped
    container_name: edu-web
    networks:
      - edu-vault-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3


  # Production Celery worker
  celery:
    build: .
    command: celery -A src.config worker -l info --concurrency=2
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=src.config.django.production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    container_name: edu-celery
    restart: unless-stopped
