line-length = 1000
target-version = "py313"

# Use standard Black formatting style
format.quote-style = "double"
format.indent-style = "space"
format.skip-magic-trailing-comma = false
format.line-ending = "auto"

[lint.isort]
combine-as-imports = true
force-wrap-aliases = true
