# Generated by Django 5.2 on 2025-05-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Form 1", "Form 1"),
                            ("Form 2", "Form 2"),
                            ("Form 3", "Form 3"),
                            ("Form 4", "Form 4"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("course_key", models.CharField(max_length=255, unique=True)),
                ("course_outline", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ExaminationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("MSCE", "MSCE"), ("JCE", "JCE"), ("IGSCE", "IGSCE")],
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
