# Generated by Django 5.1.3 on 2025-01-05 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_ware", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userquestionset",
            old_name="question_set_ids",
            new_name="question_list_ids",
        ),
    ]
