# Generated by Django 5.1.3 on 2025-04-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "iframe_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "sub_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_ware.subtopic",
                    ),
                ),
            ],
        ),
    ]
