# Generated by Django 5.1.3 on 2025-02-05 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_ware", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCategoryProgress",
        ),
    ]
