# Generated by Django 5.1.3 on 2025-02-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0002_delete_usercategoryprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionset",
            name="grading_mode",
            field=models.BooleanField(default=False),
        ),
    ]
