# Generated by Django 5.1.3 on 2025-04-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0002_learningobjective"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LearningObjective",
        ),
    ]
