# Generated by Django 5.1.3 on 2025-01-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_ware",
            "0002_rename_question_set_ids_userquestionset_question_list_ids",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
    ]
