# Generated by Django 5.1.3 on 2025-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0003_userquestionset_grading_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="flash_card_description",
            field=models.TextField(blank=True, default="FlashCard Description"),
        ),
    ]
