# Generated by Django 5.2 on 2025-05-03 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0003_delete_learningobjective"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defaultquestionset",
            name="sub_topic",
        ),
        migrations.RemoveField(
            model_name="subtopic",
            name="flash_card_description",
        ),
        migrations.RemoveField(
            model_name="userquestionattempts",
            name="sub_topic",
        ),
        migrations.RemoveField(
            model_name="userquestionset",
            name="sub_topic",
        ),
        migrations.CreateModel(
            name="LearningObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "block_id",
                    models.TextField(blank=True, db_index=True, null=True, unique=True),
                ),
                (
                    "sub_topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objective",
                        to="course_ware.subtopic",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="defaultquestionset",
            name="learning_objective",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course_ware.learningobjective",
            ),
        ),
        migrations.AddField(
            model_name="userquestionattempts",
            name="learning_objective",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="course_ware.learningobjective",
            ),
        ),
        migrations.AddField(
            model_name="userquestionset",
            name="learning_objective",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course_ware.learningobjective",
            ),
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "sub_topic_id",
                        "learning_objective_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "learning_objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_ware.learningobjective",
                    ),
                ),
                (
                    "sub_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_ware.subtopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Category",
                "verbose_name_plural": "Question Categories",
            },
        ),
        migrations.DeleteModel(
            name="SubTopicIframeID",
        ),
    ]
