# Generated by Django 5.1.3 on 2025-01-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0003_alter_category_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="course_ware.course",
            ),
        ),
    ]
