# Generated by Django 5.1.3 on 2025-01-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_ware", "0004_alter_category_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("tags", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Core Element",
                "verbose_name_plural": "Core Elements",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Skill", "verbose_name_plural": "Skills"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={
                "verbose_name": "Learning Objective",
                "verbose_name_plural": "Learning Objectives",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="core_element",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_element",
                to="course_ware.coreelement",
            ),
        ),
    ]
