# Generated by Django 5.2 on 2025-05-03 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0004_remove_defaultquestionset_sub_topic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultquestionset",
            name="learning_objective",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_ware.learningobjective",
            ),
        ),
        migrations.AlterField(
            model_name="edxuser",
            name="email",
            field=models.EmailField(blank=True, help_text="edX email", max_length=254),
        ),
        migrations.AlterField(
            model_name="edxuser",
            name="username",
            field=models.CharField(
                help_text="edX username", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="learningobjective",
            name="block_id",
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userquestionattempts",
            name="learning_objective",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="course_ware.learningobjective",
            ),
        ),
        migrations.AlterField(
            model_name="userquestionset",
            name="learning_objective",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_ware.learningobjective",
            ),
        ),
    ]
