# Generated by Django 5.1.3 on 2025-01-24 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_ware", "0005_coreelement_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="description",
        ),
    ]
