# Generated by Django 5.2 on 2025-05-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0005_alter_defaultquestionset_learning_objective_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questioncategory",
            name="category_id",
            field=models.CharField(db_index=True, default="hello", max_length=255),
            preserve_default=False,
        ),
    ]
