# Generated by Django 5.1.3 on 2025-01-25 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0006_remove_category_description_remove_topic_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultQuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_list_ids",
                    models.JSONField(help_text="References to MongoDB question IDs."),
                ),
                (
                    "topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_question_set",
                        to="course_ware.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Default Question Set",
                "verbose_name_plural": "Default Question Sets",
            },
        ),
    ]
