# Generated by Django 5.2 on 2025-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0006_questioncategory_category_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questioncategory",
            name="pk",
        ),
        migrations.RemoveField(
            model_name="questioncategory",
            name="sub_topic",
        ),
        migrations.AddField(
            model_name="questioncategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
