# Generated by Django 5.1.3 on 2025-01-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_ware", "0007_defaultquestionset"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="defaultquestionset",
            constraint=models.CheckConstraint(
                condition=models.Q(("question_list_ids__len", 9)),
                name="default_question_list_length_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="userquestionset",
            constraint=models.CheckConstraint(
                condition=models.Q(("question_list_ids__len", 9)),
                name="user_question_list_length_check",
            ),
        ),
    ]
