# Generated by Django 5.2 on 2025-05-05 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0007_remove_questioncategory_pk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningobjective",
            name="sub_topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objective",
                to="course_ware.subtopic",
            ),
        ),
    ]
