# Generated by Django 5.2 on 2025-05-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0008_alter_learningobjective_sub_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questioncategory",
            name="learning_objective",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_ware.learningobjective",
            ),
        ),
    ]
