# Generated by Django 5.1.3 on 2025-01-25 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_ware",
            "0008_defaultquestionset_default_question_list_length_check_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultquestionset",
            name="topic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="course_ware.topic"
            ),
        ),
        migrations.AlterField(
            model_name="userquestionset",
            name="topic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="course_ware.topic"
            ),
        ),
    ]
