# Generated by Django 5.2 on 2025-05-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0009_alter_questioncategory_learning_objective"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAssessmentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "ACTIVE"), ("graded", "GRADED")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("no_sql_attempt_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "learning_objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="course_ware.learningobjective",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_attempts",
                        to="course_ware.edxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Assessment Attempt",
                "verbose_name_plural": "User Assessment Attempts",
            },
        ),
        migrations.DeleteModel(
            name="UserQuestionAttempts",
        ),
        migrations.AddConstraint(
            model_name="userassessmentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user", "learning_objective"),
                name="unique_active_attempt",
            ),
        ),
    ]
