# Generated by Django 5.1.3 on 2025-01-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0009_alter_defaultquestionset_topic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="is_completed",
        ),
    ]
