# Generated by Django 5.1.3 on 2025-01-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_ware", "0010_remove_topic_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionattempts",
            name="question_metadata_description",
            field=models.JSONField(
                default={
                    "v1.0.0": {
                        "guidance": "Complete the practice set to assess your knowledge level",
                        "status": "Not Started",
                    }
                },
                help_text="Stores status information and guidance for questions",
            ),
        ),
    ]
