# Generated by Django 5.2 on 2025-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_ware",
            "0010_userassessmentattempt_delete_userquestionattempts_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuestionGrades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
