# Generated by Django 5.2 on 2025-05-08 06:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0011_userquestiongrades"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserQuestionGrades",
        ),
        migrations.RemoveField(
            model_name="userassessmentattempt",
            name="no_sql_attempt_ids",
        ),
        migrations.AddField(
            model_name="userassessmentattempt",
            name="assessment_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
