# Generated by Django 5.1.3 on 2025-01-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0011_userquestionattempts_question_metadata_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquestionattempts",
            name="question_metadata_description",
            field=models.JSONField(
                default={
                    "v1.0.0": {
                        "guidance": "Complete the practice set to assess your knowledge level",
                        "learning_mode": "normal",
                        "mode_guidance": "Answer and complete 2 out of 3 questions for each difficulty level (easy, medium, and hard) to finish the section.",
                        "status": "Not Started",
                    }
                },
                help_text="Stores status information and guidance for questions",
            ),
        ),
        migrations.CreateModel(
            name="TopicIframeID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iframe_id",
                        to="course_ware.topic",
                    ),
                ),
            ],
        ),
    ]
