# Generated by Django 5.2 on 2025-05-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EdxUser",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        help_text="edX user ID",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="edX username", max_length=255, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="edX email", max_length=254
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "edX User",
                "verbose_name_plural": "edX Users",
            },
        ),
    ]
