# Generated by Django 5.2 on 2025-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="edxuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
