# Generated by Django 5.1.3 on 2024-11-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToolConsumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuer", models.CharField(max_length=255, unique=True)),
                ("client_id", models.CharField(max_length=255, unique=True)),
                ("auth_login_url", models.URLField()),
                ("auth_token_url", models.URLField()),
                ("key_set_url", models.URLField()),
                ("private_key", models.TextField()),
                ("public_key", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
