# Generated by Django 5.1.3 on 2024-11-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lti_provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolconsumer",
            name="auth_login_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="toolconsumer",
            name="auth_token_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="toolconsumer",
            name="client_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="toolconsumer",
            name="issuer",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="toolconsumer",
            name="key_set_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="toolconsumer",
            name="private_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="toolconsumer",
            name="public_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
