# Generated by Django 5.1.3 on 2025-04-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0002_learningobjective"),
        ("course_ware_ext", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_id", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("VIDEO", "video"), ("PDF", "pdf"), ("HTML", "htmL")],
                        max_length=20,
                    ),
                ),
                (
                    "sub_topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="course_ware.subtopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Content",
                "verbose_name_plural": "Course Contents",
            },
        ),
        migrations.CreateModel(
            name="HTMLContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_study_notes", models.BooleanField(default=False)),
                (
                    "content_checksum",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "estimated_read_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated reading time in minutes",
                        null=True,
                    ),
                ),
                (
                    "course_content",
                    models.OneToOneField(
                        limit_choices_to={"content_type": "htmL"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="html_metadata",
                        to="course_ware_ext.coursecontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PDFContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Size in KB", null=True
                    ),
                ),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "download_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "course_content",
                    models.OneToOneField(
                        limit_choices_to={"content_type": "pdf"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_metadata",
                        to="course_ware_ext.coursecontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "transcript_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "video_source_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "course_content",
                    models.OneToOneField(
                        limit_choices_to={"content_type": "video"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_metadata",
                        to="course_ware_ext.coursecontent",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="coursecontent",
            index=models.Index(
                fields=["content_type"], name="course_ware_content_8ca4bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursecontent",
            index=models.Index(
                fields=["block_id"], name="course_ware_block_i_5ec752_idx"
            ),
        ),
    ]
