# Generated by Django 5.1.3 on 2025-01-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_ware_ext", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicext",
            name="description",
            field=models.TextField(help_text="Description of the topic"),
        ),
    ]
