# Generated by Django 5.1.3 on 2025-02-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_ware", "0001_initial"),
        ("course_ware_ext", "0002_delete_usercategorymastery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryext",
            name="bonus_points_available",
        ),
        migrations.CreateModel(
            name="TopicMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(default=0, help_text="Total points earned in this topic"),
                ),
                (
                    "mastery_achievements",
                    models.JSONField(
                        default={},
                        help_text="List of specific achievements earned in this category",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mastery_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("mastered", "Mastered"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_mastery",
                        to="course_ware.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_mastery",
                        to="course_ware.edxuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Skill Mastery",
                "verbose_name_plural": "User Skill Mastery",
            },
        ),
    ]
