# Generated by Django 5.1.3 on 2025-04-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_ware_ext",
            "0002_coursecontent_htmlcontent_pdfcontent_videocontent_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecontent",
            name="sub_topic",
        ),
        migrations.RemoveField(
            model_name="htmlcontent",
            name="course_content",
        ),
        migrations.RemoveField(
            model_name="videocontent",
            name="course_content",
        ),
        migrations.DeleteModel(
            name="PDFContent",
        ),
        migrations.DeleteModel(
            name="HTMLContent",
        ),
        migrations.DeleteModel(
            name="CourseContent",
        ),
        migrations.DeleteModel(
            name="VideoContent",
        ),
    ]
