# Generated by Django 5.1.3 on 2025-01-20 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_ware_ext", "0002_alter_topicext_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoryext",
            old_name="detailed_description",
            new_name="description",
        ),
    ]
