# Generated by Django 5.1.3 on 2025-01-22 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_ware_ext", "0003_rename_detailed_description_categoryext_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoryext",
            options={
                "verbose_name": "Skill Extension",
                "verbose_name_plural": "Skill Extensions",
            },
        ),
        migrations.AlterModelOptions(
            name="topicext",
            options={
                "verbose_name": "Learning Objective Extension",
                "verbose_name_plural": "Learning Objective Extensions",
            },
        ),
        migrations.AlterModelOptions(
            name="usercategorymastery",
            options={
                "verbose_name": "User Skill Mastery",
                "verbose_name_plural": "User Skill Masteries",
            },
        ),
    ]
