# Generated by Django 5.1.3 on 2025-02-07 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_ware", "0003_userquestionset_grading_mode"),
        ("course_ware_ext", "0003_remove_categoryext_bonus_points_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicmastery",
            name="topic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_mastery",
                to="course_ware.topic",
            ),
        ),
    ]
