# Generated by Django 5.1.3 on 2025-01-25 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_ware_ext",
            "0004_alter_categoryext_options_alter_topicext_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bookresource",
            name="url",
            field=models.URLField(
                default="http://www.YourDomain.com",
                help_text="URL to the book",
                validators=[django.core.validators.URLValidator()],
            ),
            preserve_default=False,
        ),
    ]
