# Generated by Django 5.1.3 on 2025-01-27 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_ware_ext", "0005_bookresource_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryext",
            name="base_mastery_points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Base points awarded for completing this category",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="categoryext",
            name="bonus_points_available",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Additional bonus points available for exceptional performance",
            ),
        ),
        migrations.AlterField(
            model_name="categoryext",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Comprehensive description of the category and its importance",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="categoryext",
            name="estimated_hours",
            field=models.PositiveIntegerField(default=0, help_text="Estimated hours to achieve mastery"),
        ),
        migrations.AlterField(
            model_name="categoryext",
            name="minimum_mastery_percentage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum percentage required for category mastery",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
